# Generated by Django 4.0.5 on 2022-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
