# Generated by Django 4.0.5 on 2022-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_restaurent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
